config/routes.rb
Rails.application.routes.draw do
  resources :pics

end

app/models/pic.rb
require 'carrierwave/orm/activerecord'

class Pic < ActiveRecord::Base

  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :set_pic, only: [:show, :edit, :update, :destroy]

  # GET /pics
  # GET /pics.json
  def index
    @pics = Pic.all
  end

  # GET /pics/1
  # GET /pics/1.json
  def show
  end

  # GET /pics/new
  def new
    @pic = Pic.new
  end

  # GET /pics/1/edit
  def edit
  end

  # POST /pics
  # POST /pics.json
  def create
    @pic = Pic.new(pic_params)
    p @pic
    respond_to do |format|
      if @pic.save
        format.html { redirect_to @pic, notice: 'Pic was successfully created.' }
        format.json { render :show, status: :created, location: @pic }
      else
        format.html { render :new }
        format.json { render json: @pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pics/1
  # PATCH/PUT /pics/1.json
  def update
    respond_to do |format|
      if @pic.update(pic_params)
        format.html { redirect_to @pic, notice: 'Pic was successfully updated.' }
        format.json { render :show, status: :ok, location: @pic }
      else
        format.html { render :edit }
        format.json { render json: @pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pics/1
  # DELETE /pics/1.json
  def destroy
    @pic.destroy
    respond_to do |format|
      format.html { redirect_to pics_url, notice: 'Pic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pic
      @pic = Pic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pic_params
      params.require(:pic).permit(:title, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ImageUploader</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pics/_form.html.erb
<%= form_for(@pic) do |f| %>
    <% if @pic.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@pic.errors.count, "error") %> prohibited this pic from being saved:</h2>

          <ul>
            <% @pic.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= form_for(@pic, :html => {:multipart => true}) do |f| %>
        ...
        <div class="field">
          <%= f.label :title %><br/>
          <%= f.text_field :title %>
        </div>
        <div class="field">
          <label>Image</label>
          <%= f.file_field :photo %>
          <%= f.hidden_field :photo_cache %>
        </div>
        <div class="actions">
          <%= f.submit %>
        </div>
    <% end %>
<% end %>

app/views/pics/edit.html.erb
<h1>Editing Pic</h1>

<%= render 'form' %>

<%= link_to 'Show', @pic %> |
<%= link_to 'Back', pics_path %>

app/views/pics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pics</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pics.each do |pic| %>
      <tr>
        <td><%= pic.title %></td>
        <td><%= link_to 'Show', pic %></td>
        <td><%= link_to 'Edit', edit_pic_path(pic) %></td>
        <td><%= link_to 'Destroy', pic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pic', new_pic_path %>

app/views/pics/new.html.erb
<h1>New Pic</h1>

<%= render 'form' %>

<%= link_to 'Back', pics_path %>

app/views/pics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @pic.title %>
  <%= image_tag @pic.photo.url %>
</p>

<%= link_to 'Edit', edit_pic_path(@pic) %> |
<%= link_to 'Back', pics_path %>